SELECT H.HACKER_ID, H.NAME, SUM(MAX_SCORE_TABLE.MAX_SCORE) AS TOTAL_SCORE
FROM HACKERS H 
JOIN 
(
    SELECT S.HACKER_ID, MAX(S.SCORE) AS MAX_SCORE
    FROM SUBMISSIONS S
    GROUP BY S.CHALLENGE_ID, S.HACKER_ID
    HAVING MAX_SCORE > 0
) AS MAX_SCORE_TABLE
ON MAX_SCORE_TABLE.HACKER_ID = H.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID ASC;