SELECT 
    CASE
        WHEN GRD.GRADE > 7 THEN STU.NAME
        ELSE NULL
    END AS NAME,
GRD.GRADE, STU.MARKS
FROM STUDENTS AS STU JOIN GRADES AS GRD
ON STU.MARKS BETWEEN GRD.MIN_MARK AND GRD.MAX_MARK
ORDER BY GRD.GRADE DESC, NAME ASC, STU.MARKS ASC;