SELECT S.HACKER_ID, H.NAME
FROM SUBMISSIONS S
JOIN HACKERS H ON H.HACKER_ID = S.HACKER_ID
JOIN CHALLENGES C ON C.CHALLENGE_ID = S.CHALLENGE_ID
JOIN DIFFICULTY D ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY S.HACKER_ID, H.NAME
HAVING COUNT(S.HACKER_ID) > 1
ORDER BY COUNT(S.HACKER_ID) DESC, S.HACKER_ID ASC;