SELECT BST.N,
CASE
    WHEN BST.P IS NULL THEN 'Root'
    WHEN EXISTS (
        SELECT BST_TEMP.P FROM BST AS BST_TEMP WHERE BST_TEMP.P = BST.N
    ) THEN 'Inner'
    ELSE 'Leaf'
END
FROM BST AS BST
ORDER BY BST.N;